// Aurora Dashboard Functions
// Created by: asarekings
// Updated: 2025-06-08 17:16:15 UTC

function updateCurrentTime() {
    const now = new Date();
    const utcString = now.toISOString().slice(0, 19).replace('T', ' ') + ' UTC';
    const element = document.getElementById('currentDateTime');
    if (element) {
        element.textContent = utcString;
    }
    
    const timeOnly = now.toISOString().slice(11, 16);
    const lastUpdated = document.getElementById('lastUpdated');
    if (lastUpdated) {
        lastUpdated.textContent = timeOnly;
    }
}

function updateMetrics() {
    const data = filterDataByRegion(MARKET_DATA[currentIndustry]);
    
    animateValue('totalMarkets', 0, data.length, 1000);
    animateValue('avgScore', 0, (data.reduce((sum, m) => sum + m.score, 0) / data.length), 1200, 1);
    animateValue('highPotential', 0, data.filter(m => m.score >= 8.0).length, 1400);
    animateValue('projectedRoi', 0, Math.max(...data.map(m => m.roi)), 1600, 0, '%');
    animateValue('riskScore', 0, (data.reduce((sum, m) => sum + m.risk, 0) / data.length), 1800, 1);
}

function animateValue(elementId, start, end, duration, decimals = 0, suffix = '') {
    const element = document.getElementById(elementId);
    if (!element) return;
    
    const range = end - start;
    const startTime = performance.now();
    
    function updateValue(currentTime) {
        const elapsed = currentTime - startTime;
        const progress = Math.min(elapsed / duration, 1);
        const easedProgress = 1 - Math.pow(1 - progress, 4);
        const current = start + (range * easedProgress);
        
        element.textContent = current.toFixed(decimals) + suffix;
        
        if (progress < 1) {
            requestAnimationFrame(updateValue);
        }
    }
    
    requestAnimationFrame(updateValue);
}

function updateTable() {
    const tableBody = document.getElementById('tableBody');
    if (!tableBody) return;
    
    const data = filterDataByRegion(MARKET_DATA[currentIndustry]).slice(0, 5);
    
    tableBody.innerHTML = data.map((market, index) => `
        <tr>
            <td><strong style="color: ${AURORA_CONFIG.colors.primary[index % AURORA_CONFIG.colors.primary.length]};">${market.name}</strong></td>
            <td>
                <div class="score-bar">
                    <div class="score-fill" style="width: ${market.score * 10}%;"></div>
                </div>
                <small><strong>${market.score}/10</strong></small>
            </td>
            <td><strong>$${market.size}B</strong></td>
            <td><strong style="color: #40407a">${market.roi}%</strong></td>
            <td><span style="color: ${market.risk < 5 ? '#26de81' : market.risk < 7 ? '#fed330' : '#ff3838'}">${market.risk}/10</span></td>
        </tr>
    `).join('');
}

function updateDashboard() {
    console.log(`🔄 Updating Aurora dashboard for ${currentIndustry} in ${currentRegion} by asarekings`);
    
    setTimeout(() => {
        updateMetrics();
        updateTable();
        updateCharts();
        updateCurrentTime();
        console.log('✅ Aurora analytics updated successfully!');
    }, 500);
}

// Button Functions
function generateAdvancedReport() {
    console.log('🎯 Generating Aurora Report by asarekings...');
    
    const data = filterDataByRegion(MARKET_DATA[currentIndustry]);
    const topMarket = data.reduce((prev, current) => (prev.score > current.score) ? prev : current);
    
    const reportContent = `# 🌟 Aurora Market Analysis Report
## ${currentIndustry.charAt(0).toUpperCase() + currentIndustry.slice(1)} Industry Analysis

**Generated by:** ${AURORA_CONFIG.author}  
**User:** ${AURORA_CONFIG.user}  
**Date:** ${AURORA_CONFIG.lastUpdated}  
**Framework:** Aurora Decision Framework v${AURORA_CONFIG.version}

## 🚀 Executive Summary
**Top Market:** ${topMarket.name} (Score: ${topMarket.score}/10, ROI: ${topMarket.roi}%)

## 📊 Key Findings
- **Markets Analyzed:** ${data.length}
- **Average Score:** ${(data.reduce((sum, m) => sum + m.score, 0) / data.length).toFixed(1)}/10
- **High Potential Markets:** ${data.filter(m => m.score >= 8.0).length}
- **Best ROI:** ${Math.max(...data.map(m => m.roi))}%

---
*Generated by Aurora AI Dashboard | Created by ${AURORA_CONFIG.author}*`;
    
    try {
        const blob = new Blob([reportContent], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `aurora-report-${currentIndustry}-${Date.now()}.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        
        alert(`🎯 Aurora Report Generated Successfully!

Industry: ${currentIndustry.charAt(0).toUpperCase() + currentIndustry.slice(1)}
Top Market: ${topMarket.name}
Created by: ${AURORA_CONFIG.author}
Time: ${AURORA_CONFIG.lastUpdated}

Report downloaded!`);
    } catch (error) {
        alert(`🎯 Aurora Report Generated!

Industry: ${currentIndustry.charAt(0).toUpperCase() + currentIndustry.slice(1)}
Top Market: ${topMarket.name}
Created by: ${AURORA_CONFIG.author}
Time: ${AURORA_CONFIG.lastUpdated}`);
    }
}

function exportAdvancedData() {
    console.log('💾 Exporting Aurora Data by asarekings...');
    
    const data = filterDataByRegion(MARKET_DATA[currentIndustry]);
    const csvContent = [
        ['Market', 'Score', 'Size', 'ROI', 'Risk', 'Timeline'],
        ...data.map(m => [m.name, m.score, m.size, m.roi, m.risk, m.timeline])
    ].map(row => row.join(',')).join('\n');
    
    try {
        const blob = new Blob([csvContent], { type: 'text/csv' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `aurora-data-${currentIndustry}-${Date.now()}.csv`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        
        alert(`💾 Aurora Data Exported Successfully!

File: aurora-data-${currentIndustry}.csv
Markets: ${data.length}
Created by: ${AURORA_CONFIG.author}
Time: ${AURORA_CONFIG.lastUpdated}

Data downloaded!`);
    } catch (error) {
        alert(`💾 Aurora Data Export Complete!

Markets: ${data.length}
Created by: ${AURORA_CONFIG.author}
Time: ${AURORA_CONFIG.lastUpdated}`);
    }
}

function runSimulation() {
    console.log('🎯 Running Aurora Simulation by asarekings...');
    
    const data = filterDataByRegion(MARKET_DATA[currentIndustry]);
    const topMarket = data.reduce((prev, current) => (prev.score > current.score) ? prev : current);
    const success = Math.round(Math.random() * 15 + 85);
    const timeToMarket = Math.round(Math.random() * 6 + 6);
    const investment = Math.round(Math.random() * 5 + 2);
    
    alert(`🎯 Aurora Simulation Complete!

📊 Analysis Results:
• Industry: ${currentIndustry.charAt(0).toUpperCase() + currentIndustry.slice(1)}
• Top Market: ${topMarket.name}
• Success Probability: ${success}%
• Time to Market: ${timeToMarket} months
• Est. Investment: $${investment}M
• Recommended Entry: ${topMarket.timeline} months

🤖 Aurora AI Recommendation:
${success >= 90 ? 'IMMEDIATE ACTION - Exceptional opportunity!' : 
  success >= 85 ? 'PROCEED - Strong market potential' : 
  'CAUTION - Additional analysis recommended'}

Generated by: ${AURORA_CONFIG.author}
Framework: Aurora v${AURORA_CONFIG.version}
Time: ${AURORA_CONFIG.lastUpdated}`);
}

// Make functions globally available
window.generateAdvancedReport = generateAdvancedReport;
window.exportAdvancedData = exportAdvancedData;
window.runSimulation = runSimulation;
